### ISSUE TITLE
Is the book still being written?

### ISSUE THREAD

**Issue by viniciusassef-openco** [LukeMathWalker/zero-to-production#122]
The site says the book should be complete by 2021. Might you say when it sould be completed?

**Comment by LukeMathWalker** [comment]
Hey!
It's very much active 😄 A looooong chapter is going to be released in the next couple of weeks - it took longer than expected because there was work to be done in the ecosystem (a whole new crate and an extensive rework of `actix-session`).

I expect to be finished early 2022, I'll update the website.
