### ISSUE TITLE
fail to compile due to sqlx-rt

### ISSUE THREAD

**Issue by cdbattags** [LukeMathWalker/zero-to-production#17]
```
Compiling sqlx-rt v0.2.0
error: one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] must be enabled
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-rt-0.2.0/src/lib.rs:9:1
   |
9  | / compile_error!(
10 | |     "one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
11 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
12 | |      'runtime-tokio-rustls'] must be enabled"
13 | | );
   | |__^

error: aborting due to previous error

error: could not compile `sqlx-rt`.
```

Amazing work on all of this so far! I'll be looking to add the "distroless" musl setup from https://dev.to/sergeyzenchenko/actix-web-in-docker-how-to-build-small-and-secure-images-2mjd soon!

**Comment by LukeMathWalker** [comment]
Sqlx released version `0.4.1` and version `0.2.0` of their CLI yesterday - they contain some breaking changes, it'll take me some time to update the code and the book - bear with me :)

**Comment by flopshot** [comment]
@cdbattags 
This is my dependency declaration for **sqlx**
```
sqlx = { version = "0.4.1", default-features = false, features = [ "macros", "postgres", "uuid", "chrono", "migrate", "runtime-tokio-native-tls"] }
```

sqlx now requires that you explicitly choose an async runtime _and_ a tsl library.

From what I gather in [this](https://users.rust-lang.org/t/any-reasons-to-prefer-native-tls-over-rustls/37626/6) thread, `native-tls` just defaults to the system's tls so I went with that for now, but `rustls` seems to be a viable option.

**Comment by pythoneer** [comment]
I think for a `musl` build `rustls` is the choice with less trouble? I remember having some time to spend in various issues/post to have openssl running.

**Comment by LukeMathWalker** [comment]
If you are going for musl then a pure Rust dependency is indeed less trouble.

**Comment by LukeMathWalker** [comment]
Latest release of the book uses `sqlx` 0.4.1, which should solve all these issues :grin:

**Comment by Pyrromanis** [comment]
I have the same problem running the reccomended command (cargo install --version=0.6.0 sqlx-cli --no-default-features --features postgres)
error: one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-
tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] must be enabled
  --> xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\sqlx-rt-0.6.1\src\lib.rs:11:1
   |
11 | / compile_error!(
12 | |     "one of the features ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
13 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
14 | |      'runtime-tokio-rustls'] must be enabled"
15 | | );
   | |_^

**Comment by LukeMathWalker** [comment]
This has been fixed in the latest release!

**Comment by dsrich** [comment]
I am using the latest of everything as of December 2022. What is going on here:

From Cargo.toml:
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "mysql"] }
tokio = { version = "1.0", features = ["full"] }

Compile Error:
error: only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] can be enabled
 --> /home/dsrich/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-rt-0.6.2/src/lib.rs:23:1
  |
23 | / compile_error!(
24 | |     "only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', \
25 | |      'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', \
26 | |      'runtime-tokio-rustls'] can be enabled"
27 | | );
  | |_^

error: could not compile `sqlx-rt` due to previous error

Any suggestions? Just makes no sense to me...

**Comment by dsrich** [comment]
Anwer to my own question from cafce25 on Stack Overflow: 

The mysql-native feature of axum_database_session requires a different sqlx-rt than sqlx with the mysql feature. You probably want to use the following instead instead.

axum_database_sessions = { version = "5.0", features = [ "sqlx"] }
