### ISSUE TITLE
Chapter 7.7: Postmark registration only by work email

### ISSUE THREAD

**Issue by MadMed677** [LukeMathWalker/zero-to-production#176]
# Description
Postmark during [registration](https://account.postmarkapp.com/sign_up) accepts only work emails. They also described it in the article
https://postmarkapp.com/blog/why-cant-i-use-gmail-address

# Suggestion
MailChimp allows you to register on your Google domain and provides a free option for a small email sender. Maybe it would help.

**Comment by c-git** [comment]
If you just want to test I actually have a [branch](https://github.com/c-git/zero-to-production/tree/Add_EmailSvc_Gmail) that works with gmail's SMTP using the lettre crate. I also have a more updated [branch](https://github.com/c-git/zero-to-production/tree/FormsForTesting) where I was working on some GUI but I also made some updates to the SMTP settings to make them easier to use without as much potential for errors by allowing you to set your password using an environment variable so you don't accidentally commit it. Happy to answer any questions you much have in that regard.

**Comment by futureproofd** [comment]
I suppose you could use mailchimp's free tier API key. You'd just need to construct the url accordingly: https://github.com/mailchimp/mailchimp-marketing-node/blob/7c1edd292e2d4732a0ea209de6b6dd38f968bf9d/src/ApiClient.js#L386

**Comment by LukeMathWalker** [comment]
This is a known limitation - it doesn't need to be a _work_ email though, it's enough for it to be an email associated with a domain you own.
If you don't have any, you can opt for an alternative email API provider (e.g. Mailchimp, as linked by @futureproofd).

**Comment by jmevel** [comment]
> This is a known limitation - it doesn't need to be a _work_ email though, it's enough for it to be an email associated with a domain you own. If you don't have any, you can opt for an alternative email API provider (e.g. Mailchimp, as linked by @futureproofd).

Just stumbled on this issue as well. 
I think this should be written in the book if a second version is released one day, otherwise many more people will just waste time on this issue as well...

**Comment by jmevel** [comment]
For anyone else passing here and wondering how the hell to make a call to Mailchimp's REST API:

First of all they have two APIs:
- [The Transactional API](https://mailchimp.com/developer/transactional/guides/quick-start/)
- [The Marketing API](https://mailchimp.com/developer/marketing/guides/quick-start/)

Here is what [their documentation](https://mailchimp.com/developer/transactional/guides/send-first-email/#transactional-vs-marketing-email) says about both:

> You can use the Marketing API for:
> - Marketing emails about an upcoming sale
> - A weekly newsletter
> - An email about an upcoming event
>
> You should choose Mailchimp Transactional when you want to send an email to an individual, usually in response to some event happening in your application. 
>
> You can use Mailchimp Transactional for:
> - Password reset emails
> - Purchase confirmation emails
> - Shipping notifications
> - Forum activity

**However, you must own a domain name in order to be able to use the Transactional API !**
So if you don't own one, like me, your only choice left is to use the Marketing API for all emails you send.

Now about calling the Marketing API, I find [their documentation](https://mailchimp.com/developer/marketing/guides/quick-start/#make-your-first-api-call) lacking of explanation in my opinion.

> curl -sS \
  "https://${dc}.api.mailchimp.com/3.0/ping" \
  --user "anystring:${apikey}" | jq -r
  
The `anystring` here refers to your username! The one you chose at the very first step when signing up with Mailchimp!

The `--user` parameter just converts the string `anystring:apikey` to a base64 value and add an `authorization` header with the value `Basic [your-base64]` to the HTTP request.
Just be sure you can successfully request their [ping endpoint](https://mailchimp.com/developer/marketing/api/ping/) before going forward (replace `${dc}` with the server name that you can find at the end of your API key (eg: `us13`)).

> GET https://us13.api.mailchimp.com/3.0/ping
> Request Headers
> authorization: Basic YW55c3RyaW5nOmFwaWtleQ==

**Comment by 9SMTM6** [comment]
As a note, if you are a student, your student mail probably will work too. It did for me. 

I actually send using my private domain, but I have no mail server set up for that and needed that for sign up. So I signed up with my student mail, and then used my own domain. 

So I don't know how the issues mentioned by postmark will affect you with a student mail if you use that as sender.
