### ISSUE TITLE
Chapter 1: How to write documentation?

### ISSUE THREAD

**Issue by 90degs2infty** [LukeMathWalker/zero-to-production#205]
Please bear with me, if the following is discussed at some point later into the book. I've only just begun reading it.

After finishing chapter 1 (which I really enjoyed being kind of new to Rust in general!) I feel like there is one thing missing in the discussion: writing documentation for one's own code using `cargo doc` (or whatever the current choice of tool is). I fully agree with the footnote on comments

> Pray that your past self wrote comments for your present self if you are about to pick up again an old project of yours.

and I guess it's a similar thing with documentation. I also think that it's kind of important to write documentation from the get-go: in my experience there is some critical threshold (in terms of code size) that once exceeded without writing documentation, a project will never catch up again and include documentation at any point in the future.

Is there a reason why writing documentation is not discussed throughout chapter 1? Is it considered out of scope for that specific chapter or even for the entire book? I guess equipping each and every code snippet throughout the book with documentation will hide the relevant information in quite an amount of background noise. So that's probably not helpful either. But maybe there is room for a brief section on how to write documentation followed by a disclaimer that the remainder of the book will leave out the documentation for a reason? :blush: 

Including a step to automatically build and deploy the documentation is another nice-to-have thing that comes to my mind - but I guess one easily leaves the book's scope here :wink: 

Anyway, thanks for this awesome book!

**Comment by LukeMathWalker** [comment]
Hey!

It's not covered in the book because I assume a baseline level of Rust knowledge—which includes how to write comments (see [relevant section of the Rust book](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#making-useful-documentation-comments)).
The rest is pretty much automated:

- `cargo doc --open` will generate documentation for all the crates in your workspace and open it in the browser;
- Documentation is automatically generated and uploaded to docs.rs every time you publish a new version of a crate.

For private crates, I don't know of any docs.rs-like solution. Most people take the HTML outputted by `cargo doc` and host it as it, since it's all static content.

Doc tests are covered later in the book when we talk about the various types of testing, although they are not particularly relevant when you are dealing with binaries—they are more useful when developing libraries.
