### ISSUE TITLE
suggest stripping --release binary as it will result in 50% smaller program

### ISSUE THREAD

**Issue by emiddleton** [LukeMathWalker/zero-to-production#42]
It might be worth mentioning stripping the release executable as this can result in a 50% decrease in program size. i.e.
```
strip target/release/zero2prod
```
Using the zero2prod code I went from 17M -> 8M.  This makes less difference with an 80M docker image but as the program grows it will become more significant.

**Comment by LukeMathWalker** [comment]
It's a deliberate omission - I prefer to explain the rationale behind what we are doing and an extensive explanation of what stripping does is beyond the scope of that section (and for most applications the size difference matters very little).
I'll add a footnote though so that interested readers can go and read about it!
