### ISSUE TITLE
Chapter 2: Executable stories - or when is somthing the subject of unit and/or integration tests

### ISSUE THREAD

**Issue by bbros-dev** [LukeMathWalker/zero-to-production#58]
Chapter 2 began with some familiar user story syntax.  I recalled Rust had a Gherkin interpreter, [in the Cucumber-Rust crate](https://cucumber.io/docs/installation/rust/?sbsearch=cucumber-rust), with an [active github project](https://github.com/bbqsrc/cucumber-rust).

Not sure if this detail is out of scope, but it brings up an issue that could be discussed here: Integration tests vs unit tests.
I struggled for years to come up with a workable approach that also let the test suites finish within a reasonable time-frame - this was the critical gotcha around unit and integration tests.

My rules of thumb were (albeit for large unit and integration test suites - but they all eventually become large ;)):
1. if code is called in a step definition, it is an integration test subject. That `fn` may still have unit tests, but those unit tests don't need to test functionality the integration test exercises.  A bit rusty here... but that guideline helped a lot in working out what delimits the unit and integration test suites.
2. A git pre-commit hook runs the changed-subset of unit tests, i.e. test file related to a file that is changed by a commit, are run prior to a commit.
3. All integration tests (running all feature/story files) are run in the CI/CD environment on push/PR.
4. If unit tests were green (required for a commit to be made), and a feature/integration test broke -> there is a critical gap in the unit test suite (Until then I found it very difficult to work out/decide when a unit test suite was incomplete in an important way).
5. All unit tests and all integration tests are run on branch merge or some such significant event.

It would be very interesting to have your thoughts/experiences on/with these issues.

Even if you decide executable scenarios/stories are off-topic/out-of-scope, some users may be working in organizations where they are required, so may would help them to know of `cucumber-rust`?

**Comment by LukeMathWalker** [comment]
> Chapter 2 began with some familiar user story syntax. I recalled Rust had a Gherkin interpreter, [in the Cucumber-Rust crate](https://cucumber.io/docs/installation/rust/?sbsearch=cucumber-rust), with an [active github project](https://github.com/bbqsrc/cucumber-rust).
> 
> Even if you decide executable scenarios/stories are off-topic/out-of-scope, some users may be working in organizations where they are required, so may would help them to know of `cucumber-rust`?

I personally do not believe Gherkin/Cucumber's approach brings a lot of value when it comes to testing and I don't feel like recommending it.
The [Arrange-Act-Assert](https://wiki.c2.com/?ArrangeActAssert) pattern we use everywhere shares a lot of similarities with the Given-When-Then used in BDD, but I don't buy into the idea that tests are clearer if written in a specification language somewhat similar to natural language compared to plain code. I don't believe the test suite is the collaboration canvas that business stakeholders and engineers should use to talk to each other.

If an engineer is approaching Rust from another programming language and they like/have experience with BDD, a `BDD Rust` Google search will easily give them pointers to all the crates they need. I don't want to push novices in that direction.

> Not sure if this detail is out of scope, but it brings up an issue that could be discussed here: Integration tests vs unit tests.
> I struggled for years to come up with a workable approach that also let the test suites finish within a reasonable time-frame - this was the critical gotcha around unit and integration tests.
> 
> My rules of thumb were (albeit for large unit and integration test suites - but they all eventually become large ;)):
> 
>     1. if code is called in a step definition, it is an integration test subject. That `fn` may still have unit tests, but those unit tests don't need to test functionality the integration test exercises.  A bit rusty here... but that guideline helped a lot in working out what delimits the unit and integration test suites.
> 
>     2. A git pre-commit hook runs the changed-subset of unit tests, i.e. test file related to a file that is changed by a commit, are run prior to a commit.
> 
>     3. All integration tests (running all feature/story files) are run in the CI/CD environment on push/PR.
> 
>     4. If unit tests were green (required for a commit to be made), and a feature/integration test broke -> there is a critical gap in the unit test suite (Until then I found it very difficult to work out/decide when a unit test suite was incomplete in an important way).
> 
>     5. All unit tests and all integration tests are run on branch merge or some such significant event.
> 
> It would be very interesting to have your thoughts/experiences on/with these issues.

My "rules" when it comes to testing:
- all user flows should be covered by "component tests" (a black-box test against the API of a deployable, using a real db, while mocking out other services the API under test relies on);
- deploy unit tests only for testing clearly isolated modules with a defined API boundary. Mostly to test failure modes that are tricky to trigger via a component test.

I shy away from the term "integration test" because it means so many different things in so many different contexts.

I work on service-oriented/microservice architectures. 
While some services can get hairier than others, test suites usually do not grow beyond 1k test cases. Component tests are generally more than fast enough to be run in the hot development loop (change code - check - run test suite), especially in a language like Rust.

My teams never prescribed having green tests as a pre-requisite to commit - I encourage devs to commit as soon as they have completed a "unit" of work (e.g. written a failing test) and we try to normalise the concept of "pushing broken code": get it in front of teammates even if it's not spotless and work together to fix it, it's ok.
But I am aware that there are as many git workflows as there are stars in the sky, so I shied away from embedding these assumptions into the book itself: apart from setting up the git repository at the very beginning, each reader is free to use version control tooling as they see fit.

**Comment by bbros-dev** [comment]
No worries. The title does say an "opinionated"... perhaps a section in the foreword about the topics on which the book is opinionated - something like what you have written above on executable stories any other topics where you think it'd save some opening an issue like this ;)

Maybe also be explicit about this not covering tooling usually found in lean-startups and such contexts where the sole-dev is dealing with marketing or UI feedback sources that balk/freeze at the sight of a JSON/HTML file never mind sitting down with a source file of tests - even if you are right there along side them. Of course as soon as two people have to simultaneously sit down to understand a requirement it stops being lean, and quickly grinds to a halt unless one of them has copious amounts of free time - which is the definition of bloated not lean ;)

**Comment by bbros-dev** [comment]
Closing as out of scope.
